### ISSUE TITLE
Missing Inventory RE2 Remake

### ISSUE THREAD

**Issue by Squirrelies** [SpeedrunTooling/SRTPluginUIRE2DirectXOverlay#3]
@brharr reported "I just ran the latest builds using this project having run your stand alone files for a long time and this is awesome. GREAT JOB. As a developer myself for almost 4 decades, great work.

I have been primarily focusing on RE2 Remake recently and I just tried this SRT manager against that and was using the DirectX Overlay. The inventory was missing, but everything else showed just fine. The image from your installation instructions leads me to believe that they should be showing and I didn't see any option in the Widgets section where I could turn it on or off.

Any help that you can provide would be be greatly appreciated."

**Comment by Squirrelies** [comment]
Can you check your plugins/SRTPluginUIRE2DirectXOverlay/ folder for a SRTPluginUIRE2DirectXOverlay.cfg file. This file is generated when you close the SRT either via 'Stop SRT' button in the manager or via CTRL+C when running directly via SRTHost64.exe. By default, "NoInventory" is set to true and needs to be flipped to false for inventory to show via the overlay.

**Comment by brharr** [comment]
This did fix the problem. As soon as I switched it to false, everything showed properly. Thanks.
